-- Reporting Automations and History

-- 1. Automation Configs (Settings for scheduled reports)
CREATE TABLE IF NOT EXISTS automation_configs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agency_id UUID, -- For future multi-tenancy support
    report_type TEXT NOT NULL, -- 'morning', 'weekly'
    is_enabled BOOLEAN DEFAULT TRUE,
    schedule_cron TEXT NOT NULL, -- cron expression
    recipients JSONB DEFAULT '[]', -- List of {name, email, whatsapp_number}
    ai_context TEXT, -- Instructions for AI personality/focus
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Report History (Audit log for AI generated insights and delivery)
CREATE TABLE IF NOT EXISTS report_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    config_id UUID REFERENCES automation_configs(id) ON DELETE SET NULL,
    report_type TEXT NOT NULL,
    data_snapshot JSONB, -- Data used to generate the report
    ai_insight TEXT, -- The actual text generated by AI
    delivery_status JSONB DEFAULT '[]', -- Status for each recipient/channel
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default rows if they don't exist
INSERT INTO automation_configs (report_type, schedule_cron, ai_context, recipients)
VALUES 
('morning', '0 8 * * *', 'Você é um consultor sênior de gestão automotiva. Seja direto, focado em números e motivacional.', '[]'),
('weekly', '0 9 * * 5', 'Você é um analista de performance. Foque em tendências da semana e pontos de melhoria para a próxima.', '[]')
ON CONFLICT DO NOTHING;

-- Multi-tenancy support if needed (checking if agencies table exists in migrations)
-- Based on 20260224160000_multi_tenancy.sql, we assume there might be an agency_id.
