// 24 ações fictícias do Plano de Ação — modelo em validação.
// Data de referência: 17/07/2026.

export const actionPlanFixtures = [
  {
    id: "pa-001",
    code: "PA-001",
    title: "Aprovar estratégia de saída dos cinco veículos críticos",
    description: "Definir margem mínima, veículos prioritários e estratégia de saída para os cinco veículos com mais de 90 dias em estoque.",
    problemOrOpportunity: "Cinco veículos críticos imobilizam capital e aumentam o tempo de estoque acima de 90 dias.",
    department: "product_stock",
    departmentLabel: "Produto e Estoque",
    strategicObjective: "reduce_inventory_capital",
    strategicObjectiveLabel: "Reduzir capital imobilizado em estoque",
    indicator: "% do Estoque > 90 Dias",
    origin: "strategic_plan",
    responsible: "Daniel",
    executor: "Rafael Souza",
    priority: "critical",
    status: "awaiting_decision",
    progress: 0,
    startDate: "01/07/2026",
    dueDate: "17/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: true,
    expectedImpact: "Potencial de liberar R$ 410.000 em capital.",
    financialImpact: 410000,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: "Aprovar margem mínima, veículos prioritários e estratégia de saída.",
  },
  {
    id: "pa-002",
    code: "PA-002",
    title: "Aprovar orçamento da área de preparação",
    description: "Aprovar o orçamento para padronizar a preparação de veículos e reduzir atrasos na entrega.",
    problemOrOpportunity: "Custo médio de preparação acima do esperado e prazo médio elevado.",
    department: "operations",
    departmentLabel: "Operações",
    strategicObjective: "standardize_operations",
    strategicObjectiveLabel: "Padronizar operações e pós-venda",
    indicator: "Custo Médio de Preparação",
    origin: "alert",
    responsible: "Daniel",
    executor: "Bruno Alves",
    priority: "high",
    status: "awaiting_decision",
    progress: 0,
    startDate: "01/07/2026",
    dueDate: "18/07/2026",
    lastUpdate: "15/07/2026",
    requiresOwner: true,
    expectedImpact: "Redução estimada de 1,8 dia no prazo médio de preparação.",
    financialImpact: 18000,
    budget: 18000,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: "Aprovar o orçamento com limite e revisão dos resultados após 30 dias.",
  },
  {
    id: "pa-003",
    code: "PA-003",
    title: "Decidir abertura da vaga de SDR",
    description: "Avaliar a contratação de um SDR para melhorar a velocidade de resposta e conversão dos leads.",
    problemOrOpportunity: "Tempo de resposta elevado e oportunidades comerciais sendo perdidas por falta de seguimento.",
    department: "people_hr",
    departmentLabel: "Marketing e Pessoas — RH",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e velocidade dos leads",
    indicator: "Conversão de Leads em Agendamentos",
    origin: "consulting",
    responsible: "Daniel",
    executor: "Ana Costa",
    priority: "medium",
    status: "awaiting_decision",
    progress: 0,
    startDate: "01/07/2026",
    dueDate: "24/07/2026",
    lastUpdate: "16/07/2026",
    requiresOwner: true,
    expectedImpact: "Potencial de aumentar a velocidade de resposta e recuperar oportunidades.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: "Validar a contratação após simular custo, capacidade e conversão mínima esperada.",
  },
  {
    id: "pa-004",
    code: "PA-004",
    title: "Executar repricing dos 11 veículos acima de 60 dias",
    description: "Aplicar novo pricing aos 11 veículos com mais de 60 dias de estoque para acelerar a saída.",
    problemOrOpportunity: "Veículos acima de 60 dias tendem a cruzar a marca de 90 dias e imobilizar mais capital.",
    department: "product_stock",
    departmentLabel: "Produto e Estoque",
    strategicObjective: "reduce_inventory_capital",
    strategicObjectiveLabel: "Reduzir capital imobilizado em estoque",
    indicator: "% do Estoque > 90 Dias",
    origin: "strategic_plan",
    responsible: "Rafael Souza",
    executor: "Rafael Souza",
    priority: "critical",
    status: "blocked",
    progress: 20,
    startDate: "05/07/2026",
    dueDate: "19/07/2026",
    lastUpdate: "10/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir o volume de veículos acima de 90 dias em 30%.",
    financialImpact: null,
    budget: null,
    blockedReason: "Aguardando definição da margem mínima.",
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-005",
    code: "PA-005",
    title: "Criar campanha de liquidação do estoque envelhecido",
    description: "Desenvolver campanha de marketing para acelerar a saída de veículos envelhecidos.",
    problemOrOpportunity: "Estoque envelhecido gera custo de oportunidade e depreciação.",
    department: "marketing",
    departmentLabel: "Marketing",
    strategicObjective: "reduce_inventory_capital",
    strategicObjectiveLabel: "Reduzir capital imobilizado em estoque",
    indicator: "Tempo de Estoque > 90 Dias",
    origin: "strategic_plan",
    responsible: "Carla Mendes",
    executor: "Carla Mendes",
    priority: "high",
    status: "not_started",
    progress: 0,
    startDate: "10/07/2026",
    dueDate: "23/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Acelerar a saída de 8 veículos envelhecidos em 30 dias.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-006",
    code: "PA-006",
    title: "Implantar política de descontos e alçadas",
    description: "Formalizar política de descontos com alçadas claras para proteger a margem de venda.",
    problemOrOpportunity: "Margem média de venda abaixo do esperado por descontos sem controle.",
    department: "commercial",
    departmentLabel: "Comercial e Financeiro",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: "Margem Média de Venda",
    origin: "alert",
    responsible: "Marcos Oliveira",
    executor: "Marcos Oliveira",
    priority: "high",
    status: "in_progress",
    progress: 75,
    startDate: "03/07/2026",
    dueDate: "20/07/2026",
    lastUpdate: "16/07/2026",
    requiresOwner: false,
    expectedImpact: "Recuperar 1,5 ponto percentual de margem média.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-007",
    code: "PA-007",
    title: "Revisar leads sem atendimento há mais de duas horas",
    description: "Implementar rotina de revisão de leads que não receberam atendimento em até duas horas.",
    problemOrOpportunity: "Leads esfriando por falta de resposta rápida.",
    department: "commercial",
    departmentLabel: "Comercial",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e produtividade comercial",
    indicator: "Conversão de Leads em Agendamentos",
    origin: "alert",
    responsible: "Marcos Oliveira",
    executor: "Marcos Oliveira",
    priority: "high",
    status: "in_progress",
    progress: 60,
    startDate: "05/07/2026",
    dueDate: "17/07/2026",
    lastUpdate: "17/07/2026",
    requiresOwner: false,
    expectedImpact: "Aumentar a conversão de leads em agendamentos em 3 pontos percentuais.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-008",
    code: "PA-008",
    title: "Implantar nova rotina de follow-up",
    description: "Estruturar rotina de follow-up pós-visita para aumentar a conversão de visitas em vendas.",
    problemOrOpportunity: "Visitas não convertidas por falta de follow-up estruturado.",
    department: "commercial",
    departmentLabel: "Comercial",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e produtividade comercial",
    indicator: "Conversão de Visitas em Vendas",
    origin: "department",
    responsible: "Marcos Oliveira",
    executor: "Marcos Oliveira",
    priority: "high",
    status: "in_progress",
    progress: 40,
    startDate: "01/07/2026",
    dueDate: "15/07/2026",
    lastUpdate: "08/07/2026",
    requiresOwner: false,
    expectedImpact: "Aumentar a conversão de visitas em vendas em 4 pontos percentuais.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-009",
    code: "PA-009",
    title: "Reduzir prazo médio de preparação para cinco dias",
    description: "Otimizar o processo de preparação para reduzir o prazo médio de 7 para 5 dias.",
    problemOrOpportunity: "Prazo médio de preparação acima do benchmark do setor.",
    department: "operations",
    departmentLabel: "Operações",
    strategicObjective: "standardize_operations",
    strategicObjectiveLabel: "Padronizar operações e pós-venda",
    indicator: "Custo Médio de Preparação",
    origin: "strategic_plan",
    responsible: "Bruno Alves",
    executor: "Bruno Alves",
    priority: "high",
    status: "in_progress",
    progress: 65,
    startDate: "03/07/2026",
    dueDate: "31/07/2026",
    lastUpdate: "15/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir o prazo médio de preparação em 2 dias.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-010",
    code: "PA-010",
    title: "Formalizar checklist de entrega dos veículos",
    description: "Criar e implantar checklist padrão de entrega dos veículos aos clientes.",
    problemOrOpportunity: "Entregas sem padronização geram retrabalho e insatisfação.",
    department: "operations",
    departmentLabel: "Operações",
    strategicObjective: "standardize_operations",
    strategicObjectiveLabel: "Padronizar operações e pós-venda",
    indicator: null,
    origin: "department",
    responsible: "Bruno Alves",
    executor: "Bruno Alves",
    priority: "medium",
    status: "awaiting_validation",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "16/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir retrabalho de entrega em 50%.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-011",
    code: "PA-011",
    title: "Finalizar PDI do gerente",
    description: "Concluir o Plano de Desenvolvimento Individual do gerente para reduzir a dependência operacional do Dono.",
    problemOrOpportunity: "Gerente sem PDI formalizado limita a delegação de responsabilidades.",
    department: "people_hr",
    departmentLabel: "Pessoas — RH",
    strategicObjective: "reduce_owner_dependency",
    strategicObjectiveLabel: "Reduzir dependência operacional do Dono",
    indicator: null,
    origin: "consulting",
    responsible: "Ana Costa",
    executor: "Ana Costa",
    priority: "high",
    status: "blocked",
    progress: 45,
    startDate: "01/07/2026",
    dueDate: "12/07/2026",
    lastUpdate: "05/07/2026",
    requiresOwner: false,
    expectedImpact: "Aumentar a autonomia do gerente em 40%.",
    financialImpact: null,
    budget: null,
    blockedReason: "Agenda do gerente ainda não confirmada.",
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-012",
    code: "PA-012",
    title: "Implantar reunião semanal de indicadores",
    description: "Estruturar reunião semanal de acompanhamento de indicadores com a equipe gestora.",
    problemOrOpportunity: "Falta de alinhamento regular sobre a evolução dos indicadores.",
    department: "general",
    departmentLabel: "Geral e Estratégia",
    strategicObjective: "reduce_owner_dependency",
    strategicObjectiveLabel: "Reduzir dependência operacional do Dono",
    indicator: null,
    origin: "consulting",
    responsible: "Marcos Oliveira",
    executor: "Marcos Oliveira",
    priority: "medium",
    status: "in_progress",
    progress: 80,
    startDate: "03/07/2026",
    dueDate: "18/07/2026",
    lastUpdate: "16/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir a presença operacional do Dono em 20%.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-013",
    code: "PA-013",
    title: "Revisar despesas extraordinárias do mês",
    description: "Auditar e classificar despesas extraordinárias para evitar impacto na rentabilidade.",
    problemOrOpportunity: "Despesas extraordinárias elevadas impactando o resultado.",
    department: "financial",
    departmentLabel: "Financeiro",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: "Despesa Total",
    origin: "alert",
    responsible: "Juliana Lima",
    executor: "Juliana Lima",
    priority: "high",
    status: "in_progress",
    progress: 50,
    startDate: "05/07/2026",
    dueDate: "17/07/2026",
    lastUpdate: "17/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir despesas extraordinárias em 15%.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-014",
    code: "PA-014",
    title: "Separar retiradas dos sócios das despesas operacionais",
    description: "Reclassificar retiradas de sócios para não distorcer as despesas operacionais.",
    problemOrOpportunity: "Retiradas misturadas com despesas operacionais dificultam a leitura do DRE.",
    department: "financial",
    departmentLabel: "Financeiro",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: "Lucro Líquido",
    origin: "diagnostic",
    responsible: "Juliana Lima",
    executor: "Juliana Lima",
    priority: "high",
    status: "not_started",
    progress: 0,
    startDate: "10/07/2026",
    dueDate: "27/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Clareza total entre retiradas e despesas operacionais.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-015",
    code: "PA-015",
    title: "Consolidar DRE gerencial mensal",
    description: "Estruturar a DRE gerencial mensal padronizada para acompanhamento do resultado.",
    problemOrOpportunity: "Falta de DRE gerencial padronizado impede a comparação mensal.",
    department: "financial",
    departmentLabel: "Financeiro",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: "Lucro Líquido",
    origin: "diagnostic",
    responsible: "Juliana Lima",
    executor: "Juliana Lima",
    priority: "high",
    status: "not_started",
    progress: 0,
    startDate: "10/07/2026",
    dueDate: "31/07/2026",
    lastUpdate: "12/07/2026",
    requiresOwner: false,
    expectedImpact: "Visibilidade clara do resultado mensal.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-016",
    code: "PA-016",
    title: "Revisar origem e qualidade dos leads",
    description: "Auditar as origens de leads e classificar por qualidade para otimizar o investimento.",
    problemOrOpportunity: "Leads de baixa qualidade gerando baixa conversão.",
    department: "marketing",
    departmentLabel: "Marketing",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e produtividade comercial",
    indicator: "Qualidade do Conteúdo",
    origin: "department",
    responsible: "Carla Mendes",
    executor: "Carla Mendes",
    priority: "medium",
    status: "in_progress",
    progress: 40,
    startDate: "05/07/2026",
    dueDate: "21/07/2026",
    lastUpdate: "15/07/2026",
    requiresOwner: false,
    expectedImpact: "Aumentar a qualidade média dos leads em 1 ponto.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-017",
    code: "PA-017",
    title: "Preparar reunião de revisão com a Consultoria",
    description: "Preparar a pauta e os materiais para a reunião de revisão do ciclo com a consultoria.",
    problemOrOpportunity: "Necessidade de alinhamento com a consultoria sobre o progresso do ciclo.",
    department: "general",
    departmentLabel: "Geral e Estratégia",
    strategicObjective: "reduce_owner_dependency",
    strategicObjectiveLabel: "Reduzir dependência operacional do Dono",
    indicator: null,
    origin: "consulting",
    responsible: "Daniel",
    executor: "Daniel",
    priority: "medium",
    status: "not_started",
    progress: 0,
    startDate: "10/07/2026",
    dueDate: "23/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Alinhamento claro com a consultoria sobre os próximos passos.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-018",
    code: "PA-018",
    title: "Atualizar premissas do ciclo estratégico",
    description: "Revisar e atualizar as premissas do ciclo estratégico com base nos resultados parciais.",
    problemOrOpportunity: "Premissas desatualizadas podem comprometer as decisões do ciclo.",
    department: "general",
    departmentLabel: "Geral e Estratégia",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: null,
    origin: "strategic_plan",
    responsible: "Daniel",
    executor: "Daniel",
    priority: "medium",
    status: "awaiting_validation",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "22/07/2026",
    lastUpdate: "15/07/2026",
    requiresOwner: false,
    expectedImpact: "Decisões do ciclo baseadas em premissas atualizadas.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-019",
    code: "PA-019",
    title: "Formalizar checklist de compra de veículos",
    description: "Criar e formalizar o checklist de compra de veículos para padronizar a aquisição.",
    problemOrOpportunity: "Compras sem checklist geram inconsistência na seleção.",
    department: "product_stock",
    departmentLabel: "Produto e Estoque",
    strategicObjective: "reduce_inventory_capital",
    strategicObjectiveLabel: "Reduzir capital imobilizado em estoque",
    indicator: null,
    origin: "department",
    responsible: "Rafael Souza",
    executor: "Rafael Souza",
    priority: "high",
    status: "completed",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "10/07/2026",
    lastUpdate: "10/07/2026",
    requiresOwner: false,
    expectedImpact: "Padronizar a compra e reduzir inconsistências.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: "10/07/2026",
    impactStatus: "partial",
    recommendation: null,
  },
  {
    id: "pa-020",
    code: "PA-020",
    title: "Atualizar política de precificação do estoque",
    description: "Revisar e atualizar a política de precificação para proteger a margem de estoque.",
    problemOrOpportunity: "Precificação desatualizada comprometendo a margem.",
    department: "product_stock",
    departmentLabel: "Produto e Estoque",
    strategicObjective: "protect_profitability",
    strategicObjectiveLabel: "Proteger a rentabilidade",
    indicator: null,
    origin: "strategic_plan",
    responsible: "Rafael Souza",
    executor: "Rafael Souza",
    priority: "high",
    status: "completed",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "14/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Recuperar 1 ponto de margem média de estoque.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: "14/07/2026",
    impactStatus: "positive",
    recommendation: null,
  },
  {
    id: "pa-021",
    code: "PA-021",
    title: "Mapear processo de pós-venda",
    description: "Mapear o processo de pós-venda para padronizar o atendimento e reduzir retrabalho.",
    problemOrOpportunity: "Pós-venda sem mapeamento gera inconsistência.",
    department: "operations",
    departmentLabel: "Operações",
    strategicObjective: "standardize_operations",
    strategicObjectiveLabel: "Padronizar operações e pós-venda",
    indicator: null,
    origin: "department",
    responsible: "Bruno Alves",
    executor: "Bruno Alves",
    priority: "medium",
    status: "completed",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "11/07/2026",
    lastUpdate: "11/07/2026",
    requiresOwner: false,
    expectedImpact: "Padronizar o pós-venda e reduzir retrabalho.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: "11/07/2026",
    impactStatus: "unmeasured",
    recommendation: null,
  },
  {
    id: "pa-022",
    code: "PA-022",
    title: "Definir SLA de resposta ao cliente",
    description: "Estabelecer o SLA de resposta ao cliente para melhorar a experiência e a conversão.",
    problemOrOpportunity: "Falta de SLA gera respostas inconsistentes e perda de oportunidades.",
    department: "commercial",
    departmentLabel: "Comercial",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e produtividade comercial",
    indicator: null,
    origin: "department",
    responsible: "Marcos Oliveira",
    executor: "Marcos Oliveira",
    priority: "high",
    status: "completed",
    progress: 100,
    startDate: "01/07/2026",
    dueDate: "09/07/2026",
    lastUpdate: "09/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir o tempo de resposta em 40%.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: "09/07/2026",
    impactStatus: "positive",
    recommendation: null,
  },
  {
    id: "pa-023",
    code: "PA-023",
    title: "Criar calendário editorial de conteúdo",
    description: "Estruturar um calendário editorial mensal para organizar a produção de conteúdo de marketing.",
    problemOrOpportunity: "Conteúdo sem planejamento gera baixa consistência e qualidade irregular.",
    department: "marketing",
    departmentLabel: "Marketing",
    strategicObjective: "improve_conversion",
    strategicObjectiveLabel: "Melhorar conversão e produtividade comercial",
    indicator: "Qualidade do Conteúdo",
    origin: "department",
    responsible: "Carla Mendes",
    executor: "Carla Mendes",
    priority: "medium",
    status: "not_started",
    progress: 0,
    startDate: "12/07/2026",
    dueDate: "28/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Aumentar a consistência do conteúdo em 50%.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
  {
    id: "pa-024",
    code: "PA-024",
    title: "Estruturar programa de integração de novos vendedores",
    description: "Criar um programa de integração (onboarding) para acelerar a produtividade de novos vendedores.",
    problemOrOpportunity: "Novos vendedores levam muito tempo para atingir produtividade plena.",
    department: "people_hr",
    departmentLabel: "Pessoas — RH",
    strategicObjective: "reduce_owner_dependency",
    strategicObjectiveLabel: "Reduzir dependência operacional do Dono",
    indicator: null,
    origin: "consulting",
    responsible: "Ana Costa",
    executor: "Ana Costa",
    priority: "high",
    status: "not_started",
    progress: 0,
    startDate: "12/07/2026",
    dueDate: "30/07/2026",
    lastUpdate: "14/07/2026",
    requiresOwner: false,
    expectedImpact: "Reduzir o tempo de onboarding de 30 para 15 dias.",
    financialImpact: null,
    budget: null,
    blockedReason: null,
    completedAt: null,
    impactStatus: null,
    recommendation: null,
  },
];