#!/usr/bin/env node
// Story 0.1 / DB-014 — Gera src/types/database.generated.ts a partir do Supabase linked.
// Strip de banner inicial ("Initialising login role...") e rodape ("A new version of Supabase CLI...").

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const OUT = resolve(process.cwd(), 'src/types/database.generated.ts');
const PROJECT_REF = 'fbhcmzzgwjdgkctlfvbo';

const HEADER = `// AUTO-GENERATED by \`npm run gen:db-types\` — DO NOT EDIT MANUALLY.
// Source: Supabase project ${PROJECT_REF} (MX GESTAO PREDITIVA)
// Regenerate after every migration: \`npm run gen:db-types\`
// CI gate: .github/workflows/db-types-diff.yml bloqueia merge se houver drift.

`;

function isNoise(line) {
  return (
    line.startsWith('Initialising login role') ||
    line.startsWith('A new version of Supabase CLI') ||
    line.startsWith('We recommend updating regularly')
  );
}

try {
  console.log('Gerando types via supabase CLI...');
  const raw = execSync('supabase gen types typescript --linked --schema public', {
    encoding: 'utf8',
    maxBuffer: 50 * 1024 * 1024,
    stdio: ['inherit', 'pipe', 'inherit'],
  });

  const clean = raw
    .split('\n')
    .filter((l) => !isNoise(l))
    .join('\n')
    .replace(/\n+$/, '\n');

  writeFileSync(OUT, HEADER + clean, 'utf8');
  const lines = clean.split('\n').length;
  console.log(`OK: ${OUT} (${lines} linhas + header)`);
} catch (err) {
  console.error('FAIL:', err.message);
  process.exit(1);
}
