export const VISIT_REASON_OPTIONS = [
  'Onboarding',
  'Diagnóstico e Treinamento Método Vendedor Profissional - Fase 1',
  'Planejamento Estratégico, Metodologia de Vendas por Multicanal, Acompanhamento Diário de Vendas, Gestão á Vista e Treinamento MVP - Fase 2',
  'Rotina do Gerente e do Vendedor, Feedback Estruturado',
  'Cultura de Resultado e Treinamento MVP - Fase 3',
  'Plano de Desenvolvimento Individual (PDI)',
  'Posicionamento de Marketing, Estratégia de Conteúdo e Tráfego Pago',
  'Análise das Implementações e Plano de Ação Trimestral',
  'Acompanhamento',
  'Modelo de Negócio',
  'Planejamento Estratégico',
  'Maximização de Receitas',
  'Eficiência em Custos',
  'Treinamento Vendedores',
  'Resultados e Plano de Ação',
  'Treinamento Venda Aprovada (Financiamento)',
  'Visita 1: Diagnóstico e Treinamento Método Vendedor Profissional',
  'Visita 2: Planejamento Estratégico, Metodologia de Vendas por Multicanal, Acompanhamento Diário de Vendas, Gestão á Vista e Treinamento MVP',
  'Visita 3: Rotina do Gerente e do Vendedor, Feedback Estruturado',
  'Visita 4: Cultura de Resultado e Treinamento MVP',
  'Visita 5: Plano de Desenvolvimento Individual (PDI)',
  'Visita 6 Online: Posicionamento de Marketing, Estratégia de Conteúdo e Tráfego Pago',
  'Visita 7: Análise das Implementações e Plano de Ação Trimestral',
  'Agenda bloqueada',
  'Evento MX',
  'Gestão dos Indicadores',
  'Acompanhar financiamento (receita adicional)',
  'Agenda bloqueada (treinamento)',
  'Treinamento Vendedores / Rotina Gerente e vendedor',
  'Processo Seletivo Gerente Comercial',
  'Rotina Comercial do Gerente',
  'Prospecção',
  'Planejamento Estratégico, Metodologia de Vendas por Multicanal, Treinamento Método Vendedor Profissional, Acompanhamento Diário de Vendas e Gestão á Vista',
  'Revisão dos Processos Críticos',
] as const

export const AGENDA_TARGET_OPTIONS = [
  'Proprietário',
  'Vendedor',
  'Gerente',
  'Todos',
  'Vendedor e Gerente',
  'Proprietário e Gerente',
  'Proprietário e Marketing',
] as const
